---
- name: Add Kubernetes repo
  yum_repository:
      name: Kubernetes
      description: Kubernetes
      file: kubernetes
      baseurl: http://yum.kubernetes.io/repos/kubernetes-el7-x86_64
      enabled: true
      gpgcakey: https://packages.cloud.google.com/yum/doc/yum-key.gpg
      gpgkey: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      gpgcheck: true
      state: present

- name: Install kubeadm
  yum:
      name: '{{ cluster_packages | list }}'
      state: latest
      update_cache: true

# Restart and Enable the services

- name: Enable and start kubelet
  systemd:
      name: kubelet
      enabled: yes
      state: restarted

- name : Enable and start docker
  systemd:
      name: docker
      enabled: yes
      state: restarted

